# ============================== Filebeat inputs ==============================

filebeat.config.inputs:
  enabled: true
  # Glob pattern for configuration loading
  path: /Users/qiufeng/go/src/github.com/elastic/beats/filebeat/inputs.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 10s

# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

# -------------------------------- Kafka Output --------------------------------
output.kafka-cluster:
  # initial brokers for reading cluster metadata
  hosts: '%{[output.hosts]}'
  cluster: '%{[output.cluster]}'

  # message topic selection + partitioning
  topic: '%{[output.topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

# ================================== Logging ===================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: debug

path.home: /Users/qiufeng/Documents/beat
path.config: /Users/qiufeng/Documents/beat
filebeat.registry.path: /Users/qiufeng/Documents/beat/registory
