# ============================== Filebeat inputs ==============================

filebeat.config.inputs:
  enabled: true
  # Glob pattern for configuration loading
  path: /home/infra/filebeat/inputs.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  reload.period: 10s

# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

# -------------------------------- Kafka Output --------------------------------
output.kafka-cluster:
  # initial brokers for reading cluster metadata
  hosts: '%{[output.hosts]}'
  cluster: '%{[output.cluster]}'

  # message topic selection + partitioning
  topic: '%{[output.topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec.adaptor:
    string: '%{[output.prefix]} %{[message]}'

#================================= updater ==================================
#updater is for fetching config from log collect service and report collecting
#progress to it.
#path is where to persist config and it must in keep with input path
filebeat.updater:
  enabled: true
  host: 127.0.0.1:8080
  user: filebeat
  password: file_beat
  period: 10s
  path: /home/infra/filebeat/inputs.d/kafka-clusters.yml
  timeout: 5s

# ================================== Logging ===================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: debug

path.home: /home/infra/filebeat
path.config: /home/infra/filebeat
filebeat.registry.path: /home/infra/filebeat/registry
